import { FounderData, Startup } from '@/types';

export const FOUNDER_DATA: FounderData = {
  name: "Shaswat Raj",
  title: "Full Stack Developer & Open Source Enthusiast",
  bio: "With over 4 years of development experience, I've worked across the entire technology stack, from creating intuitive frontends with React and Next.js to designing scalable backends with Node.js. I'm deeply committed to open source and have contributed to numerous projects that help the developer community. My approach combines technical excellence with creative problem-solving to deliver exceptional digital experiences.",
  avatar: "https://shaswat.live/_next/image?url=%2Fprofile.jpg&w=640&q=75",
  location: "Jharkhand, India",
  email: "sh20raj@gmail.com",
  linkedin: "https://linkedin.com/in/sh20raj",
  twitter: "https://twitter.com/SH20RAJ",
  github: "https://github.com/sh20raj",
  website: "https://shaswat.live",
  resume: "https://docs.google.com/document/d/1_c8_1teca5JlCIFnsSC0rqoHcvxD5VJrlE-DeKZSXf4/edit?usp=sharing",
  codepen: "https://codepen.io/sh20raj",
  devto: "https://dev.to/sh20raj",
  totalFunding: "$2M+",
  successfulExits: 0,
  yearsExperience: 4,
  totalValuation: "$15M+",
  companiesActive: 5,
  skills: [
    "JavaScript (8+ years, 95%)",
    "TypeScript (5+ years, 90%)",
    "HTML (10+ years, 98%)",
    "CSS (10+ years, 95%)",
    "React & Next.js",
    "Node.js",
    "PHP (7+ years, 85%)",
    "Python (4+ years, 80%)",
    "C (3+ years, 75%)",
    "C++ (2+ years, 70%)"
  ],
  specializations: [
    "Full-Stack Development",
    "Frontend Architecture",
    "Backend Development",
    "UI/UX Design",
    "Open Source Development",
    "Technical Writing"
  ],
  values: [
    "Clean, maintainable code that solves real problems",
    "Continuous learning and sharing knowledge",
    "Creating accessible, user-friendly interfaces",
    "Excellence in every project undertaken"
  ],
  projects: "50+",
  availability: "Open to opportunities",
  remoteWork: "Available worldwide",
  interests: ["Coffee enthusiast", "Podcast listener", "Lifelong learner", "Remote work advocate", "Tech collector"],
  quote: "I believe that great software is born at the intersection of technical excellence and thoughtful user experience. My goal is to create digital products that not only work flawlessly but also bring joy to those who use them."
};

export const STARTUPS_DATA: Startup[] = [
  {
    id: 1,
    name: "Creaovate",
    description: "AI-powered content creation ecosystem that helps creators, marketers, and businesses generate viral content ideas, streamline workflows, and dominate social trends at lightning speed using Meta's Llama 3 AI.",
    phase: "building",
    fundingStage: "bootstrapped",
    founded: "2024",
    funding: "$0",
    employees: "1-3",
    teamSize: 2,
    industry: "AI/ML",
    logo: "/next.svg",
    website: "https://creaovate.shraj.workers.dev",
    location: "Global (Remote)",
    buildingProgress: 75,
    monthlyRevenue: "$0",
    growthRate: "Pre-revenue",
    achievements: ["50K+ Content Ideas Generated", "10K+ Active Creators", "200+ Global Locations", "Sub-100ms Response Time"],
    keyMetrics: {
      users: "10K+",
      revenue: "Pre-revenue",
      growth: "Scaling"
    },
    pitchDeckUrl: "/pitch-decks/creaovate-seed.pdf"
  },
  {
    id: 2,
    name: "Reflecto",
    description: "Simple yet powerful AI-enhanced journaling platform with mood tracking, Luna AI assistant for natural language search, and time capsules for reflection. Designed for busy people who want meaningful self-reflection.",
    phase: "building",
    fundingStage: "bootstrapped",
    founded: "2024",
    funding: "$0",
    employees: "1-3",
    teamSize: 2,
    industry: "Productivity",
    logo: "/globe.svg",
    website: "https://reflecto.netlify.app",
    location: "Remote",
    buildingProgress: 70,
    monthlyRevenue: "$0",
    growthRate: "Pre-revenue",
    achievements: ["1K+ Active Journalers", "Luna AI Assistant", "Free Forever Plan", "Privacy-First Design"],
    keyMetrics: {
      users: "1K+",
      revenue: "Free",
      growth: "Growing"
    },
    pitchDeckUrl: "/pitch-decks/reflecto-seed.pdf"
  },
  {
    id: 3,
    name: "SketchFlow",
    description: "Advanced real-time collaborative diagramming and whiteboarding platform with AI-powered suggestions, split-screen markdown integration, and enterprise-grade security. Used by 10K+ teams globally.",
    phase: "building",
    fundingStage: "series-a",
    founded: "2023",
    funding: "$10M",
    valuation: "$45M",
    employees: "15-25",
    teamSize: 20,
    industry: "Productivity",
    logo: "/vercel.svg",
    website: "https://sketchflow.space",
    location: "Global",
    buildingProgress: 85,
    monthlyRevenue: "$85K",
    growthRate: "20% MoM",
    achievements: ["Series A: $10M", "10K+ Active Users", "1M+ Diagrams Created", "99.9% Uptime"],
    keyMetrics: {
      users: "10K+",
      revenue: "$1M ARR",
      growth: "20% MoM"
    },
    needsFunding: false,
    pitchDeckUrl: "/pitch-decks/sketchflow-series-b.pdf"
  },
  {
    id: 4,
    name: "Daksha",
    description: "Sacred agentic AI companion that goes beyond conversation to become a deeply personal ally. Emotionally intelligent, memory-aware assistant for mental wellness, personal growth, and authentic human connection.",
    phase: "ideation",
    fundingStage: "bootstrapped",
    founded: "2024",
    funding: "$0",
    employees: "1-2",
    teamSize: 1,
    industry: "AI/ML",
    logo: "/window.svg",
    website: "https://daksha.pages.dev",
    location: "Remote",
    monthlyRevenue: "$0",
    growthRate: "Pre-launch",
    achievements: ["Beta Waitlist Active", "Mental Health Focus", "Privacy-First Design", "AI Companion Technology"],
    keyMetrics: {
      users: "Pre-launch",
      revenue: "Pre-revenue",
      growth: "Development"
    },
    needsFunding: true,
    pitchDeckUrl: "https://daksha.pages.dev/PITCH.pdf"
  },
  {
    id: 5,
    name: "Unistory",
    description: "Revolutionary college-only social platform with verified .edu authentication, combining social networking, academic collaboration, mental wellness, career networking, and campus life management for students worldwide.",
    phase: "ideation",
    fundingStage: "pre-seed",
    founded: "2024",
    funding: "$0",
    employees: "2-5",
    teamSize: 3,
    industry: "Social Media",
    logo: "/file.svg",
    website: "https://unistory.pages.dev/dashboard",
    location: "Global",
    monthlyRevenue: "$0",
    growthRate: "Pre-launch",
    achievements: ["Comprehensive MVP Built", "University Partnership Discussions", "2.5K+ Pre-launch Interest", "Multi-layer Platform Design"],
    keyMetrics: {
      users: "Pre-launch",
      revenue: "Pre-revenue",
      growth: "Development"
    },
    needsFunding: true,
    pitchDeckUrl: "https://destiny-hardware-0e7.notion.site/Unistory-Pitch-deck-211cd0ed0c2580bfae29cf6004e28d06"
  },
  // Legacy startups for comparison
  {
    id: 6,
    name: "TechFlow AI",
    description: "AI-powered workflow automation platform helping businesses streamline their operations with intelligent process optimization.",
    phase: "active",
    fundingStage: "series-a",
    founded: "2023",
    funding: "$15M",
    valuation: "$45M",
    employees: "45-50",
    teamSize: 47,
    industry: "AI/ML",
    logo: "/next.svg",
    website: "https://techflow.ai",
    location: "San Francisco, CA",
    monthlyRevenue: "$450K",
    growthRate: "25%",
    achievements: ["YC W23", "Forbes 30 Under 30", "Best AI Startup 2024"],
    keyMetrics: {
      users: "10K+",
      revenue: "$5.4M ARR",
      growth: "25% MoM"
    }
  },
  {
    id: 7,
    name: "HealthTrack Pro",
    description: "Digital health platform connecting patients with healthcare providers through telemedicine and health monitoring.",
    phase: "fundraising",
    fundingStage: "series-a",
    founded: "2021",
    funding: "$12M",
    employees: "30-35",
    teamSize: 33,
    industry: "HealthTech",
    logo: "/vercel.svg",
    website: "https://healthtrack.pro",
    location: "Boston, MA",
    needsFunding: true,
    pitchDeckUrl: "/pitch-decks/healthtrack-series-b.pdf",
    monthlyRevenue: "$280K",
    growthRate: "18%",
    achievements: ["FDA Approved", "HIPAA Compliant", "500K+ Active Users"],
    keyMetrics: {
      users: "500K+",
      revenue: "$3.4M ARR",
      growth: "18% MoM"
    }
  },
  {
    id: 8,
    name: "BuildBot AI",
    description: "AI-powered construction management platform that automates project planning and resource allocation for residential development.",
    phase: "building",
    fundingStage: "seed",
    founded: "2024",
    funding: "$3M",
    employees: "12-15",
    teamSize: 14,
    industry: "AI/ML",
    logo: "/window.svg",
    website: "https://buildbot.ai",
    location: "Denver, CO",
    buildingProgress: 65,
    monthlyRevenue: "$85K",
    growthRate: "35%",
    achievements: ["Techstars Denver", "Construction Tech Innovation Award"],
    keyMetrics: {
      users: "2.5K+",
      revenue: "$1.0M ARR",
      growth: "35% MoM"
    }
  }
];